[package]
name = "fltk-flow"
version = "0.1.0"
edition = "2018"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
description = "A flow widget wrapping Fl_Flow"
repository = "https://github.com/fltk-rs/fltk-flow"
documentation = "https://docs.rs/fltk-flow"
keywords = ["gui", "widgets", "graphics"]
categories = ["gui"]
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }
fltk-sys = { git = "https://github.com/fltk-rs/fltk-rs" }
paste = "1"

[build-dependencies]
fltk-sys = { git = "https://github.com/fltk-rs/fltk-rs" }
fltk-build = "0.1"
cc = "1"